### ISSUE TITLE
How to utilize sensor data

### ISSUE THREAD

**Issue by MustacheEmperor** [pomeroyb/Create2Control#5]
Not sure if this is the right place to ask this but I think you and I are most of the internet's knowledgebase on programming this. 

How exactly do you call the robot for sensor data? I've been trying to just get the status on the bumper sensor (id 7) to start with but printing the output of bot.sensors('7') or bot.get_packet('7') always returns "None", not even 0, regardless of whether I'm pushing the bumper or not. Am I fundamentally misunderstanding how you get data from this thing (I think I am)? I'm trying to get it to detect the bumper being bumped and run another function after - do I need to implement Stream for that? 

Thanks

**Comment by pomeroyb** [comment]
Whoops, there is no return in the "success" case of the get_packet method, and the documentation comment is wrong. It shouldn't return the value of the packet, just whether or not the packet was succesfully received.

Try

```
bot.get_packet(7)

print json.dumps(bot.sensor_state['wheel drops and bumps'], indent=4, sort_keys=False)
```

get_packet directly overwrites the bot's sensor state with the updated sensor info, rather than returning the value and relying on the user to update the sensor state.

**Comment by MustacheEmperor** [comment]
That makes more sense! Thanks! Gonna keep adding more functionality and will keep you updated with pull requests as stuff is working...gonna write a function to scroll messages across the LCD soon I think.
